spring.profiles.active: development
---
server:
  port: 9090
spring:
  profiles: development
  application:
    name: ex-product
  resources:
    chain:
      enabled: true
  cloud:
    stream:
      bindings:
        productEventsPublisherChannel:
          binder: rabbit
          destination: product.exchange
          contentType: application/json
          producer:
            requiredGroups: orderProducts
        productAddedEventsPublisherChannel:
          binder: rabbit
          destination: productAdded.exchange
          contentType: application/json
          producer:
            requiredGroups: orderProducts
zuul:
  sensitiveHeaders : ''
ribbon:
  ReadTimeout: 100000
logging:
  level:
    root: INFO
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE